test_list=['Gojo Satorou','Gojo Satoru', 'Nezuko Kamado','Marin Kitagawa', 'Tanjirou Kamado',
           'Zero Two', 'Manjiro Sano', 'Hu Tao', 'Sukuna', 'Sung JinWoo', 
           'Baal', 'Killua Zoldyck', 'Mai Sakurajima', 'Zenitsu Agatsuma', 
           'Monkey D. Luffy', 'Jinx', 'Shinobu Kochou', 'Yuji Itadori', 
           'Naruto Uzumaki', 'Zoro Roronoa', 'Giyuu Tomioka', 'Mikasa Ackermann', 
           'Eren Jaeger', 'Kyoujurou Rengoku', 'Gawr Gura', 'Megumi Fushiguro', 
           'Ken Ryuguji', 'Itachi Uchiha', 'Inosuke Hashibira', 'Ken Kaneki', 
           'Rias Gremory', 'Shouko Komi', 'Miku Nakano', 'Kaedehara Kazuha', 
           'Shouto Todoroki', 'Yumeko Jabami', 'Nobara Kugisaki', 'Ganyu', 'Zhongli', 
           'Violet Evergarden', 'Eula', 'Akeno Himejima', 'Jolyne Cujoh', 'Chifuyu Matsuno',
            'Jotaro Kujo', 'Rimuru Tempest', 'Izuku Midoriya', 'Sasuke Uchiha', 'Siesta', 
            'Hayase Nagatoro', 'Katsuki Bakugou', 'Nino Nakano', 'Kaguya Shinomiya', 
            'Toge Inumaki', 'Izumi Miyamura', 'Keisuke Baji', 'Megumin', 'Kamisato Ayaka', 
            'Kyouko Hori', 'Kakashi Hatake', 'Osamu Dazai', 'Gon Freecss', 'Himiko Toga', 
            'Chika Fujiwara', 'Arataki Itto', 'Cha HaeIn', 'Dio Brando', 'Venti', 'Kanna Kamui', 
            'Shoyo Hinata', 'Rin Tohsaka', 'Mitsuri Kanroji', 'Childe', 'Nico Robin', 'Caitlyn', 
            'Hisoka', 'Mori Calliope', 'Kirito', 'Keqing', 'Saitama', 'Esdeath', 'Hinata Hyuuga', 
            'Chizuru Mizuhara', 'Miko Yotsuya', 'Diluc', 'Kurumi Tokisaki', 'Light Yagami', 
            'Itsuki Nakano', 'Kento Nanami', 'Sanji', 'Roxy Migurdia', 'Tobio Kageyama', 'Albedo', 
            'Watson Amelia', 'Hange Zoe', 'Ichigo Kurosaki', 'Maki Zenin', 'Joseph Joestar', 
            'Gyro Zeppeli', 'Klee', 'Giorno Giovanna', 'Ai Hayasaka', 'Kusuo Saiki', 'Kurapika', 
            'Shouko Nishimiya', 'Takemichi Hanagaki', 'Dabi', 'Sangonomiya Kokomi', 'Raphtalia', 
            'Kenma Kozume', 'Yotsuba Nakano', 'Erza Scarlet', 'Kurisu Makise', 'Lelouch Lamperouge', 
            'Yoimiya', 'Paimon', 'Takt Asahina', 'Kaori Miyazono', 'Senkuu', 'Armin Arlert', 
            'Yukino Yukinoshita', 'Kanao Tsuyuri', 'Rikka Takanashi', 'Madara Uchiha', 'Karma Akabane', 
            'Johnny Joestar', 'Kaeya', 'Shigeo Kageyama', 'Ai Ooto', 'Vladilena Milizé', '2B', 'Takashi Mitsuya', 
            'Natsu Dragneel', 'jomae Ina nis',]
